name: bash

on:
  pull_request:
    paths: bash/**.sh

defaults:
  run:
    shell: bash
    working-directory: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: make lint
